# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
