# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namelist',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
